services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "mysite.wsgi.application"
      - "--bind"
      - "0.0.0.0:8080"
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volums:
      - ./mysite/database:/app/database
    envfile:
      - .env
